### ISSUE TITLE
Error: It looks like you are using Playwright Sync API inside the asyncio loop. Please use the Async API instead.

### ISSUE THREAD

**Issue by harrisonham** [itsjafer/schwab-api#11]
Hello,
I am working on implementing the schab-api package with my trading strategy, and have gotten the error:

"Error: It looks like you are using Playwright Sync API inside the asyncio loop. Please use the Async API instead."

After some investigation, it looks like there is an issue with using the schwab-api within spyder. Is there a workaround for this? I saw that there was a way to get things to run on google colab, but the solution does not work locally for either spyder or jupyter notebook.

**Comment by hrpomrx** [comment]
Seeing this also, when running in Jupyter notebook.

**Comment by vstadnytskyi** [comment]
Seeing this also, when running in Jupyter notebook in Colab.

**Comment by publius001** [comment]
still seeeing this one in JupyterLab. Any workarounds?

**Comment by itsjafer** [comment]
The only workaround I could see is using async playwright to login to Schwab since the sync_playwright library is inherently incompatible with Jupyter

**Comment by NelsonDane** [comment]
@itsjafer could this be added with an option when creating using `api = Schwab()`. Like doing `api = Schwab(async=True)` or something like that? Can have the option default to False but be there for Jupyter or Google Colab.

**Comment by itsjafer** [comment]
Could one of you provide an example Colab notebook that faces this error so I can debug?

**Comment by itsjafer** [comment]
Brief update on this: I tested out an asynchronous version and it seemed to work well with Jupyter/Colab, though it wasn't actually able to login as expected. I'll continue looking into offering an async solution in the meantime.

**Comment by 4rumprom** [comment]
I made an async login a few weeks ago that I was running on streamlit.
I'll try to see if I can retrieve it...

**Comment by publius001** [comment]
Cool!
Thanks

**Comment by 4rumprom** [comment]
So I found the code! I'll create a new pull requests as soon as my current one for option strategies went through.

**Comment by itsjafer** [comment]
Hi version 0.4.0 is now compatible with asynchronous environments. Thank you @4rumprom for your contribution!
