### ISSUE TITLE
self.page.wait_for_load_state('networkidle') Causing Login Failure

### ISSUE THREAD

**Issue by kimardenmiller** [itsjafer/schwab-api#13]
Seems Schwab may have made a change about a month ago causing all instances of a wait for `networkidle` load state to fail. I've solved it in my own code by simply removing all `self.page.wait_for_load_state('networkidle')` lines, as they don't seem to be needed and it seems Playwright suggests the same generally.

**Comment by victorfaria87** [comment]
Hey Kim, 
I had the same longing issue, but your solution isn’t working for me.
With "Headless=False", Disabled the Synematic two step verification and manually added webkit browser to trusted browsers.
I am now able to login without any issue(changed the login script to just log in), but then can’t perform any other operations.
do you know if am going in the wrong directions here?

**Comment by itsjafer** [comment]
I've gone ahead and removed the wait for networkidle. I was able to confirm that login was failing before the change and working after the change. schwab-api 0.2.3 should contain the fix
