### ISSUE TITLE
Call Positions not showing up in account info

### ISSUE THREAD

**Issue by amaten69** [itsjafer/schwab-api#15]
Creating this issue to track a pull request to add functionality to return call and other child positions in an account.

**Comment by amaten69** [comment]
Oh guess we can post to branches. Just adding this for loop to schwab.py added call positions to account info (tested with several accounts)

`for position in security_group["Positions"]:
                    positions.append(
                        Position(
                            position["DefaultSymbol"],
                            position["Description"],
                            int(position["Quantity"]),
                            float(position["Cost"]),
                            float(position["MarketValue"])
                        )._as_dict()
                    )

                    for child_position in position["ChildOptionPositions"]:
                        positions.append(
                            Position(
                                child_position["DefaultSymbol"],
                                child_position["Description"],
                                int(child_position["Quantity"]),
                                float(child_position["Cost"]),
                                float(child_position["MarketValue"])
                            )._as_dict()
                        )`

**Comment by itsjafer** [comment]
Hi, could you create a pull request to add this functionality? I'd be happy to approve!

**Comment by itsjafer** [comment]
Actually, I'll go ahead and add this myself and push the change to the next version
