### ISSUE TITLE
Auto renew token

### ISSUE THREAD

**Issue by dougbrowning** [itsjafer/schwab-api#21]
The token times out in about 2 mins "invalid_token"}']. In the TD API it would auto refresh that token.

Know anything on that?

thanks again

**Comment by itsjafer** [comment]
Hi @dougbrowning, I've added auto-renewal of tokens in 0.3.3, please take a look!

**Comment by dougbrowning** [comment]
Thanks but now this line is failing on me
api.quote([stock])
    spy_quotes =  api.quote([stock])
AttributeError: 'Schwab' object has no attribute 'quote'

What changed?  thanks
