### ISSUE TITLE
quote function change?

### ISSUE THREAD

**Issue by dougbrowning** [itsjafer/schwab-api#23]
I see it is now quotes = api.quote_v2?  
But I get this message
(['{"errors":[{"id":"59667069-9c6f-052a-9d4e34795291","status":"500","title":"InternalServerError","details":"Server '
  'Error - Error while getting quotes"}]}'],
 False)

Not sure what changed but nothing is working for me now.
thanks

**Comment by itsjafer** [comment]
I'm not quite able to reproduce this, could you give me the exact code you're running?

**Comment by dougbrowning** [comment]
Well it was 
quotes = api.quote(["SPY   231219C00470000"])
but now it says that function no longer exists and all I see is this now
quotes = api.quote_v2(["SPY   231219C00470000"])

![image](https://github.com/itsjafer/schwab-api/assets/6051277/4337bff0-6e87-4f10-894b-17c14a62f3e5)

Well now I got quotes = api.quote_v2(["SPY   231219C00470000"]) to start working.

Why was the function changed?  Hard to keep code in sync.

thanks

**Comment by itsjafer** [comment]
You can expect stability in function names going forward. Glad you got it working!

**Comment by dougbrowning** [comment]
I see the difference now.  The options are what stopped working
quotes = api.quote_v2(["SPY   231219C00474000"])
  does not work
quotes = api.quote_v2(["SPY"])
  does work.

Did you change the format for options?

thanks
