### ISSUE TITLE
Playwright Sync API issue

### ISSUE THREAD

**Issue by einemal** [itsjafer/schwab-api#3]
Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

How do I do that?

**Comment by itsjafer** [comment]
Could you give some more detail on how you're calling this library?

**Comment by einemal** [comment]
Yes, sure, here is my code and error:

from schwab_api import Schwab

api = Schwab.get_instance(
    username=username,
    password=password,
    user_agent=user_agent
)

--------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-2-c4be5496a202> in <module>
      5 user_agent = "Chrome/93.0.4577.63"
      6 
----> 7 api = Schwab.get_instance(
      8     username=username,
      9     password=password,

~\AppData\Roaming\Python\Python38\site-packages\schwab_api\schwab.py in get_instance(**kwargs)
     66         """
     67         if not Schwab.__instance:
---> 68             Schwab(**kwargs)
     69         return Schwab.__instance
     70 

~\AppData\Roaming\Python\Python38\site-packages\schwab_api\schwab.py in __init__(self, **kwargs)
     33             raise Exception("Schwab expects the following constructor variables: `username`, `password`, `user_agent`")
     34 
---> 35         self.playwright = sync_playwright().start()
     36 
     37         self.context = self.playwright.chromium.launch_persistent_context(

~\AppData\Roaming\Python\Python38\site-packages\playwright\sync_api\_context_manager.py in start(self)
     73 
     74     def start(self) -> SyncPlaywright:
---> 75         return self.__enter__()
     76 
     77     def __exit__(self, *args: Any) -> None:

~\AppData\Roaming\Python\Python38\site-packages\playwright\sync_api\_context_manager.py in __enter__(self)
     40             own_loop = loop
     41         if loop.is_running():
---> 42             raise Error(
     43                 """It looks like you are using Playwright Sync API inside the asyncio loop.
     44 Please use the Async API instead."""

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

**Comment by itsjafer** [comment]
It looks to me like the error is suggesting that you didn't provide a username, password, or user_agent. i.e. your code should look something like this:

```
from schwab_api import Schwab

username = "your_username"
password = "your_password"
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" # Example user agent

api = Schwab.get_instance(
username=username,
password=password,
user_agent=user_agent
)
```

**Comment by eggyBones** [comment]
I am having this same issue. I am extremely new to GitHub and coding in general so it's probably just user error but I did follow your suggestions and I still got the same message (Error: It looks like you are using Playwright Sync API inside the asyncio loop. Please use the Async API instead). Any further suggestions would be appreciated  :)

**Comment by itsjafer** [comment]
@eggyBones couod you send the code you’re running and the full error?

**Comment by eggyBones** [comment]
!pip install schwab-api
!python -m playwright install
!pip install pyotp
________________________________________________
from schwab_api import Schwab

username = "exampleUsername"
password = "examplePassword"
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"

api = Schwab.get_instance(
username= username,
password= password,
user_agent= user_agent
)

api.login(screenshot= False)
    # Get information about all accounts holdings
account_info = api.get_account_info()
print(account_info)
________________________________________________
________________________________________________
ERROR:root:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 33))

Attempting to login
___________________________________________________________
Error                                     Traceback (most recent call last)
<ipython-input-2-a096223532fa> in <module>()
     11 )
     12 
---> 13 api.login(screenshot=True)
     14     # Get information about all accounts holdings
     15 account_info = api.get_account_info()

2 frames
/usr/local/lib/python3.7/dist-packages/playwright/sync_api/_context_manager.py in __enter__(self)
     42             raise Error(
     43                 """It looks like you are using Playwright Sync API inside the asyncio loop.
---> 44 Please use the Async API instead."""
     45             )
     46 

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

**Comment by itsjafer** [comment]
Try this:

`from schwab_api import Schwab

username = "exampleUsername"
password = "examplePassword"

api = Schwab.get_instance(
  username= username,
  password= password,
)

api.login(screenshot= False)
# Get information about all accounts holdings
account_info = api.get_account_info()
print(account_info) `

**Comment by eggyBones** [comment]
Just tried it and I'm still having the same issue. I'll continue trying to troubleshoot. by the way I love this project and what you're doing here. hopefully soon I'll have the python knowledge to help out.

**Comment by itsjafer** [comment]
It looks like you might running this in a Jupyter notebook or a Google Colab? Could you give me some more information about the environment you're running it in? I appreciate the kind words, by the way!

**Comment by eggyBones** [comment]
Yes! running it in the basic version of Google Colab with default settings.

**Comment by itsjafer** [comment]
hi @eggyBones, I've created a colab notebook that runs the API (I've tested it myself). It seems like colab requires installing a few other dependencies as well as running the script in a specific way.

You can find the notebook here: https://github.com/itsjafer/schwab-api/blob/main/Schwab_API_Example.ipynb

**Comment by eggyBones** [comment]
@itsjafer I appreciate all of the support! excited to implement your API into my project. Thanks!
