### ISSUE TITLE
Locking My Account

### ISSUE THREAD

**Issue by p-norris** [itsjafer/schwab-api#45]
Hi,

Thank you for all your working making this api.

Starting yesterday, I'm getting locked out of my account when I run a script. I'm not sure if this has to do with the recent addition of dotenv, but when using the dotenv code, I could not log in at all, so I removed it. Without dotenv, I logged in a number of times and tested my script, but the last two attempts required a call to Schwab in order to get back into the account.

Do you know of this problem and have a solution?

Thank you,

Phil

**Comment by 4rumprom** [comment]
I'm using dotenv for local troublshooting and I don't have any issues.
I don't want to presume but my immediate guess is that the credentials are wrong and Schwab locks the account after too many failed attempts.
I recommend you print the credentials before passing them to api.login() and make sure they are correct.

**Comment by p-norris** [comment]
The error message says that api is expecting a str and getting an object. I tried getting around that a couple of times, but when I removed the `os.getenv`, it worked fine. Until the next day, and the day after that after getting unblocked.

Getting blocked may be my issue, I was getting a quote in a while loop every second. Is there a limit on requesting info?

**Comment by 4rumprom** [comment]
It's possible that getting quotes too frequently will get your account
blocked. Just as a guideline, https://polygon.io/ allows 5 calls per minute
on their free account.
When you call Schwab to unlock, maybe they can tell you more as to why it
was locked.

However, that doesn't fully explain why an object is passed when a string
is expected. Do you have the exact error message?
