### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by 4rumprom** [itsjafer/schwab-api#46]
![image](https://github.com/itsjafer/schwab-api/assets/84041172/3cb3ebeb-7ab4-43e7-8007-f9141f7ebfa3)

It seems the user-agent passed along with the playwright identification is causing this page to show up, which in turn causes the identification to fail as of this morning.

A quick fix would be to update the user-agent string, however, a more robust solution is needed.

**Comment by 4rumprom** [comment]
I think the most robust fix is to change the user agent to firefox, which is actually the browser used with playwright and to update the version the one used by playwright.
Hence, when playwright is outdated, the login will fail. Once playwright is updated, the USER_AGENT "constant" will update alongside.

**Comment by MaxxRK** [comment]
I agree with the above comment, but if the website does not want to load correctly in firefox for some reason the below library could be used to get a "popular" user agent each time it is called. This should accomplish the same thing.

https://pypi.org/project/fake-useragent/

**Comment by 4rumprom** [comment]
Yes, that was my first thought. However, this schwab-API currently hardcoded firefox anyways. If anything else entered in SessionManager.browserType, it defaults to webkit, which actually doesn't work with Schwab. At least not on the two machines I tried it on.
Additionally:
- fake-agent is another dependency to manage & update.
- if using github actions (which I am), there are some issues with configuring fake-agent to get it to work as it will not allow to connect to willshouse.com. See developer section: https://pypi.org/project/fake-useragent/
I've made a simple tweak to authenticate.py and tested it. I works now.
Until this change is approved, I recommend adding the following line to your code right after the api call:

# Initialize our schwab instance
api = Schwab()

version = api.browser.version
usr_agent = f"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:{version}) Gecko/20100101 Firefox/{version}"
api.page = api.browser.new_page(
    user_agent = usr_agent,
    viewport = { 'width': 1920, 'height': 1080 }
    )

**Comment by MaxxRK** [comment]
I believe your solution is best then for sure. Very simple. I just went into site packages and hardcoded a Firefox user agent to v123.00 and it worked fine for me as well. If it does not get approved, I will use the above.

**Comment by itsjafer** [comment]
Out on vacation, but I've approved the change. Will try to identify a more robust solution to this type of thing going forward

**Comment by tristanpenman** [comment]
Not sure if this is still relevant, but I had another workaround for this. This is what I implemented while experimenting with the Playwright async API:

```
try:
    async with self.page.expect_navigation():
        await self.page.frame(name=login_frame).press("[placeholder=\"Password\"]", "Enter")
except TimeoutError:
    raise Exception("Login was not successful; please check username and password")

# Handles out-of-date user agent
if await self.page.get_by_text("Time to Update Your Browser").is_visible():
    async with self.page.expect_navigation():
        await self.page.click("button:text(\"Continue\")")

if self.page.url != urls.trade_ticket():
    return False

await self.page.wait_for_selector("#_txtSymbol")
```

If you think something like this would be useful, and sufficiently robust, I can raise a PR once https://github.com/itsjafer/schwab-api/pull/51/files has been merged.
