### ISSUE TITLE
Symantec ID not working anymore

### ISSUE THREAD

**Issue by micheleissa** [itsjafer/schwab-api#52]
Hello,
First let me thank you for this great package! 
Login started to fail today and even logging into the app or web is not working stating security code is not valid. I called customer support and when they tried the Symantec Id I had or any new one generated by the script it is not working. Would it be possible for you to look into that? I mean is the vipaccess package not the latest version or its author might have addressed the issue in a newer version ?
Sorry if I'm making some assumptions here, my python knowledge is rather limited.

Michel

**Comment by 4rumprom** [comment]
Did you try updating to 0.3.11?
It has a fix for login issues.

**Comment by micheleissa** [comment]
I have upgraded to 0.3.11
<img width="1070" alt="image" src="https://github.com/itsjafer/schwab-api/assets/16201881/298a9cd3-78f6-49fc-9376-3ebebbe6fe27">
Am I missing something? Now I tried generating a completely new TOTP and it works fine via the web app, mobile app fine but still the login routine falls into the SMS flow like the following
<img width="799" alt="image" src="https://github.com/itsjafer/schwab-api/assets/16201881/7aa69329-11e2-4ea2-94d1-28446a7cfd01">

**Comment by 4rumprom** [comment]
I did some testing. If your password or login are incorrect, you'd raise the error:
Exception: Login was not successful; please check username and password|
When the TOTP is either missing or entered incorrectly, it will return that error message you are seeing.

You might really want to make sure you're passing the correct TOTP.

**Comment by micheleissa** [comment]
I tried a brand newly generated TOTP and it did not work then I retried the original one and the second time it worked. I'm pretty sure I'm sending the correct secret every time but anyway it might have been copy/paste error. Thanks for the response. I'm closing the issue.

**Comment by 4rumprom** [comment]
When was your daylight savings time change? As of this morning, I am having this issue and we just changed time. I wonder if it may be linked to time change.

**Comment by micheleissa** [comment]
I believe it was like 2 days ago.

**Comment by micheleissa** [comment]
@4rumprom  are you still facing the issue? I had some  login time outs this morning.

**Comment by 4rumprom** [comment]
Not anymore but the issue was a change of the landing page url on the schwab side.
I saw a pull request to check for the updated url on schwab with version 0.3.12 but it's not deployed yet.
I've submitted a modification in my async pull request to make it more robust by looking for the keywords app/trade in the url rather than looking for an exact url match.

In the meantime, you may want to update urls.py under the schwab_api package with the following code:
`def trade_ticket():
    return "https://client.schwab.com/app/trade/tom/trade?ShowUN=YES"`

**Comment by micheleissa** [comment]
With the change you suggested it is working now. I hope Schwab releases the API soon the traversing of the UI is very flaky.

**Comment by 4rumprom** [comment]
Currently, the login is what's problematic. Once logged in, the Schwab API
is already being used.
You'd probably still want to have a python wrapper to interface with the
Schwab API anyways, as it was the case with TDA. Once authentication can be
done via the API, it will be better.

**Comment by micheleissa** [comment]
I understand Schwab API is being used after the login, what I meant is the how currently the login is implemented. I also used to use TDA when it was working. Even at my job when QA teams decide to do E2E via Selenium the tests are fragile due to the nature of the system under test being  the UI.

**Comment by micheleissa** [comment]
Hey @4rumprom  quick question.
now your async changes are merged in. This means I can run a script via Jupyter right? sorry if the question is silly :) I'm using this as an opportunity to strengthen my skills in python.

**Comment by 4rumprom** [comment]
I didn't specifically try it on Jupyter but yes, the idea was that running
async would be more compatible with spyder / jupyter / steamlit or other
systems that don't support synchronous playwright.

**Comment by micheleissa** [comment]
yea I tried in jupyter but getting the following error, it seems to be conflicting with Jupyter's running event loop. 
<img width="1259" alt="image" src="https://github.com/itsjafer/schwab-api/assets/16201881/056cb844-543c-4140-90c1-8d10df9c120b">

**Comment by 4rumprom** [comment]
Do you mind opening a new issue for this? In your new issue, if you could also please share what code are you running. Did you try running the example to test it?

**Comment by micheleissa** [comment]
I have copied and pasted from the example but I can try again then open a new issue.
