### ISSUE TITLE
Can't load https://itsjafer.com/#/schwab to get TOTP

### ISSUE THREAD

**Issue by alxwlfe** [itsjafer/schwab-api#6]
I'm just stumbling on this and went  to try to get a TOTP from https://itsjafer.com/#/schwab but the page doesn't load for me. Getting the console errors below in Chrome (same error in incognito).

![image](https://user-images.githubusercontent.com/49067637/145664279-b2c0c1de-1124-4da2-84a2-d1859c0d2645.png)

Super excited about this API method of working with Schwab though!

**Comment by itsjafer** [comment]
Hey, thanks for pointing this out. I thought this was an issue on your end but I was actually able to reproduce it and found it was a pretty small bug; I'm surprised I didn't notice this before. Just fixed, could you confirm it works?

**Comment by alxwlfe** [comment]
It works! Awesome, thanks for the quick fix (and for creating this!)

**Comment by alxwlfe** [comment]
Oh, quick question, I noticed the 'Generate TOTP' option isn't listed on that page - do you still have the 'easy' method available there? If not I'll work through generating one the hard way 😅
