### ISSUE TITLE
Login Error: waiting for locator("select#landingPageOptions")

### ISSUE THREAD

**Issue by NelsonDane** [itsjafer/schwab-api#63]
The past few days this issue has been popping up for me:

```
Error logging in to Schwab: Frame.select_option: Timeout 30000ms exceeded.
Call log:
waiting for locator("select#landingPageOptions")

Traceback (most recent call last):
  File "/Users/ndane/GitHub/auto-rsa/schwabAPI.py", line 35, in schwab_init
    schwab.login(
  File "/Users/ndane/GitHub/auto-rsa/.venv/lib/python3.12/site-packages/schwab_api/authentication.py", line 103, in login
    return asyncio.run(self._async_login())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ndane/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/ndane/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ndane/.pyenv/versions/3.12.2/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ndane/GitHub/auto-rsa/.venv/lib/python3.12/site-packages/schwab_api/authentication.py", line 145, in _async_login
    await self.page.frame(name=login_frame).select_option("select#landingPageOptions", index=3)
  File "/Users/ndane/GitHub/auto-rsa/.venv/lib/python3.12/site-packages/playwright/async_api/_generated.py", line 5335, in select_option
    await self._impl_obj.select_option(
  File "/Users/ndane/GitHub/auto-rsa/.venv/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 679, in select_option
    return await self._channel.send("selectOption", params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ndane/GitHub/auto-rsa/.venv/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ndane/GitHub/auto-rsa/.venv/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Frame.select_option: Timeout 30000ms exceeded.
Call log:
waiting for locator("select#landingPageOptions")
```

This occurs whether saving the session cache or not.

**Comment by davidacrook** [comment]
This also has been happening to me the last few days.  90% fails.  Same error: "waiting for locator("select#landingPageOptions")"  I looked here to see if anyone else had the same problem.  Schwab must have made a change.

**Comment by NelsonDane** [comment]
I did a little debugging myself and here's what I found:

The script uses this to login on the home page (schwab.com)
![image](https://github.com/itsjafer/schwab-api/assets/47427072/19ff71f7-157d-4e96-8998-f9188efb3362)
But when opened using Playwright it doesn't load in:
![image](https://github.com/itsjafer/schwab-api/assets/47427072/64e30162-d274-475a-8a67-0b9b4ebfccb0)
This leads to the timeout error.

Here's some things I noticed while troubleshooting:
1. In my normal browser (Brave), schwab.com redirects to schwab.com/client-home, but it doesn't do this in Playwright (not sure if this is important or not). Going directly to /client-home didn't change anything.
2. Commenting out `await stealth_async(self.page)` in `authentication.py` causes the above iframe to show up, but login fails:
![image](https://github.com/itsjafer/schwab-api/assets/47427072/13db4758-4a07-4f89-aa8b-e891659bcbc8)
(Which makes sense since it's probably blocking the automation)
3. Everything loads and shows up correctly accessing this login link https://client.schwab.com/Areas/Access/Login, but of course some selectors would need to be changed for a successful login. Maybe we want to switch to this page instead?

Hopefully this is helpful and a fix is found soon :)

**Comment by NelsonDane** [comment]
I found a fix that worked for me and created a PR. Would love to know if this also works for you @cnMuggle @davidacrook

**Comment by davidacrook** [comment]
Thanks Nelson!  I get farther now, but then get a 30 second timeout error on this line:  
await self.page.wait_for_url(re.compile(r"app/trade"), wait_until="domcontentloaded") # Making it more robust than specifying an exact url which may change.

**Comment by davidacrook** [comment]
Testing Nelson's change on Windows and WSL, 5 tries each: Windows (Python 3.12) - 0 successes, 5 failures.  Linux (Python 3.10) - 2 successes, 3 failures.  The successes take 17 seconds and it used to take 10 seconds, so something changed on Schwab's side.  @NelsonDane, what is your operating environment that this works successfully in?

**Comment by NelsonDane** [comment]
@davidacrook Thanks for the reply and for testing. I've tested on: (both headless and not)
1. MacOS 14.5 Apple Silicon (Python 3.12.2) - Success
2. Linux (Docker - Python 3.12-slim image) Intel Server - Success

However, when I tested it this morning on a Windows 11 VM (Python 3.12.2) I found that it failed to the same timeout error as previously. The iframe also didn't load and "strobed" like in the image I sent above (when ran non-headless).

Also this morning, I found that commenting the `await stealth_async(self.page)` caused it to work on both MacOS and Windows without giving the "call customer support" error as seen above, which is very strange. So there is something that `schwab.com` does not like being blocked by that function on Windows. I can do more testing today and mess with the stealth config more in my Windows VM and see if I can get it any further.

**Comment by NelsonDane** [comment]
Doing more digging, the `playwright-stealth` module seems to be problematic https://github.com/AtuboDad/playwright_stealth/issues, with some users saying newer versions of playwright [broke it](https://github.com/AtuboDad/playwright_stealth/issues/16). This [issue](https://github.com/AtuboDad/playwright_stealth/issues/31) gave some options to disable, but none of them would work in my Windows VM (but did on MacOS/Linux). 

Perhaps this module is doing more harm than good? It's at least something to look into more.

**Comment by itsjafer** [comment]
Don't have a ton of bandwidth to test myself, but can we try freezing to playwright 1.4.4 (before the breaking changes) and see if that resolves the issue for now?

**Comment by NelsonDane** [comment]
Checking today, it seems that the iframe is no longer blocked, and it's working without any changes needed for me now. Strange, perhaps Schwab updated/fixed something on their side

**Comment by cnMuggle** [comment]
I am able to login with @NelsonDane's change in a Linux machine. Just commenting out "await stealth_async(self.page, config)" doesn't work for me. I's strange that my Windows machine can login sometimes without the change (cannot login last Friday, but works Monday today, while the same code cannot work on a Linux machine until I applied the NelsonDane's change). I do see under Linux that without commenting "await stealth_async(self.page, config)", the login box is blacked out.
![image](https://github.com/user-attachments/assets/0e70f219-0ebf-4ee0-9d6e-43d82fb45ed2)

**Comment by Sabermoose19** [comment]
I still have this issue even on Linux.

**Comment by NelsonDane** [comment]
I'm getting the same thing as @cnMuggle, currently getting the first image, but then using https://github.com/itsjafer/schwab-api/pull/64 allows it to login properly.

**Comment by itsjafer** [comment]
release 0.4.3 contains the fix. Thanks @NelsonDane for the PR!

**Comment by WinesProof** [comment]
I've moved to using the official Schwab API instead of this project, but I found the changes in #64 to be necessary in order to automate the token creation flow (the one you need to do every ~7 days). So I just wanted to say thank you @NelsonDane for solving that as well.
